{ ... }:{
  imports = [
    ./settings.nix
    ./nfs.nix
    ./add-replay-gain.nix
    ./matrix-conduit.nix
    ./qbittorrent.nix
    ./jellyfin.nix
    ./surrealdb.nix
    ./monero.nix
    ./elasticsearch.nix
    ./uptime-kuma.nix
    ./nix-serve.nix
    ./netdata.nix
    ./navidrome.nix
    ./netdata.nix
    ./openssh.nix
    ./hydra.nix
    ./innernet.nix
    ./prowlarr.nix
    ./syncthing.nix
    ./clean-unused-files.nix
    ./nix-daemon.nix
    ./virtualisation.nix
    ./shokoserver.nix
    ./flaresolverr.nix
    ./sonarr.nix
    ./fireflyiii.nix
    ./engelsystem.nix
    ./postgresql.nix
  ];
}
